# Generated by Django 6.0 on 2025-12-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(max_length=4)),
                ("name", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("municipality", models.TextField()),
            ],
        ),
    ]
