# Generated by Django 6.0 on 2025-12-25 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="airport",
            name="code",
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_steps",
                        to="routes.route",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.airport"
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("route", "sequence")},
            },
        ),
        migrations.AddField(
            model_name="route",
            name="waypoints",
            field=models.ManyToManyField(
                related_name="flights_through",
                through="routes.RouteWaypoint",
                to="routes.airport",
            ),
        ),
    ]
