# Generated by Django 6.0 on 2025-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_alter_airport_code_routewaypoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(default="ZZ", max_length=2),
            preserve_default=False,
        ),
    ]
