# Generated by Django 6.0 on 2025-12-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classNumber', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('expiration', models.DateField()),
            ],
        ),
    ]
