# Generated by Django 6.0 on 2025-12-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medical",
            name="expiration",
        ),
        migrations.RemoveField(
            model_name="medical",
            name="name",
        ),
        migrations.AddField(
            model_name="medical",
            name="expiration_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
