# Generated by Django 6.0 on 2025-12-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicals", "0002_remove_medical_expiration_remove_medical_name_and_more"),
        ("pilots", "0006_remove_pilot_medical_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medical",
            name="expiration_years",
        ),
        migrations.AddField(
            model_name="medical",
            name="number",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="pilot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical",
                to="pilots.pilot",
            ),
            preserve_default=False,
        ),
    ]
