# Generated by Django 6.0 on 2025-12-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicals", "0003_remove_medical_expiration_years_medical_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medical",
            name="number",
        ),
        migrations.AddField(
            model_name="medical",
            name="examination_date",
            field=models.DateField(default="2025-07-19"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="examiner_designation_number",
            field=models.CharField(default="000001959", max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="examiner_name",
            field=models.CharField(default="Alvin Nayan, MD", max_length=50),
            preserve_default=False,
        ),
    ]
