# Generated by Django 6.0 on 2025-12-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulator",
            old_name="sim_type",
            new_name="sim_class",
        ),
        migrations.AddField(
            model_name="plane",
            name="plane_class",
            field=models.CharField(
                choices=[("Single Engine Land", "Sel"), ("Multi Engine Land", "Mel")],
                default="SEL",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
