# Generated by Django 6.0 on 2025-12-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
        ('medicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('PI', 'Pilot'), ('I', 'Instructor'), ('E', 'Examiner'), ('PA', 'Passenger')], max_length=2)),
                ('licenses', models.ManyToManyField(related_name='licenses', to='licenses.license')),
                ('medical_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.medical')),
            ],
        ),
    ]
