# Generated by Django 6.0 on 2025-12-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('medicals', '0002_remove_medical_expiration_remove_medical_name_and_more'),
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='licenses',
            field=models.ManyToManyField(null=True, related_name='licenses', to='licenses.license'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='medical_certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicals.medical'),
        ),
    ]
