# Generated by Django 6.0 on 2025-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
        ("pilots", "0002_alter_pilot_licenses_alter_pilot_medical_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilot",
            name="licenses",
            field=models.ManyToManyField(
                related_name="licenses", to="licenses.license"
            ),
        ),
    ]
