# Generated by Django 6.0 on 2025-12-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
        ("medicals", "0002_remove_medical_expiration_remove_medical_name_and_more"),
        ("pilots", "0003_alter_pilot_licenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilot",
            name="licenses",
            field=models.ManyToManyField(
                blank=True, related_name="licenses", to="licenses.license"
            ),
        ),
        migrations.AlterField(
            model_name="pilot",
            name="medical_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicals.medical",
            ),
        ),
    ]
