# Generated by Django 6.0 on 2025-12-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilots", "0004_alter_pilot_licenses_alter_pilot_medical_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pilot",
            name="licenses",
        ),
    ]
