# Generated by Django 6.0 on 2025-12-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilots", "0005_remove_pilot_licenses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pilot",
            name="medical_certificate",
        ),
    ]
