# Generated by Django 6.0 on 2025-12-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('route', models.JSONField(default=list)),
                ('pic_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('sic_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('flight_training_received', models.DecimalField(decimal_places=1, max_digits=19)),
                ('xc_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('solo_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('day_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('night_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('actual_instrument_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('simulated_instrument_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('day_landings', models.IntegerField()),
                ('day_fullstop_landings', models.IntegerField()),
                ('night_landings', models.IntegerField()),
                ('night_fullstop_landings', models.IntegerField()),
                ('single_engine_land_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('notes', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_flight_instructor', to='pilots.pilot')),
                ('passengers', models.ManyToManyField(blank=True, related_name='as_passenger', to='pilots.pilot')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_flight_pilot', to='pilots.pilot')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('subject', models.TextField()),
                ('endorsement', models.TextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ground_instructor', to='pilots.pilot')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ground_pilot', to='pilots.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('route', models.JSONField(default=list)),
                ('simulated_instrument_time', models.DecimalField(decimal_places=1, max_digits=19)),
                ('notes', models.TextField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_sim_pilot', to='pilots.pilot')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plane')),
            ],
        ),
    ]
