# Generated by Django 6.0 on 2025-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_flight_flight_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ground",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ground",
            name="ground_time",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulator",
            name="sim_time",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
