# Generated by Django 6.0 on 2025-12-21 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_ground_duration_ground_ground_time_and_more"),
        ("pilots", "0003_alter_pilot_licenses"),
        ("planes", "0002_rename_sim_type_simulator_sim_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="instructor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_sim_instructor",
                to="pilots.pilot",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simulator",
            name="plane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planes.simulator"
            ),
        ),
    ]
