# Generated by Django 6.0 on 2025-12-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_simulator_instructor_alter_simulator_plane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ground",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ground",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulator",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulator",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
