# Generated by Django 6.0 on 2025-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0006_alter_ground_time_end_alter_ground_time_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="single_engine_land_time",
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulator",
            name="route",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
