# Generated by Django 6.0 on 2025-12-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0007_remove_flight_single_engine_land_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="solo_time",
        ),
    ]
