# Generated by Django 6.0 on 2025-12-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0008_remove_flight_solo_time"),
        ("pilots", "0004_alter_pilot_licenses_alter_pilot_medical_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_flight_instructor",
                to="pilots.pilot",
            ),
        ),
    ]
