# Generated by Django 6.0 on 2025-12-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0009_alter_flight_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ground",
            name="endorsement",
        ),
    ]
