# Generated by Django 6.0 on 2025-12-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0010_remove_ground_endorsement"),
        ("pilots", "0004_alter_pilot_licenses_alter_pilot_medical_certificate"),
        ("planes", "0002_rename_sim_type_simulator_sim_class_and_more"),
        ("routes", "0003_airport_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.route",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SimulatorFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("sim_time", models.DecimalField(decimal_places=1, max_digits=19)),
                (
                    "simulated_instrument_time",
                    models.DecimalField(decimal_places=1, max_digits=19),
                ),
                ("notes", models.TextField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_sim_instructor",
                        to="pilots.pilot",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_sim_pilot",
                        to="pilots.pilot",
                    ),
                ),
                (
                    "plane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planes.simulator",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Simulator",
        ),
    ]
