# Generated by Django 6.0 on 2025-12-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0011_alter_flight_route_alter_simulator_route_and_more"),
        ("planes", "0002_rename_sim_type_simulator_sim_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulatorflight",
            name="plane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planes.simulator"
            ),
        ),
    ]
