# Generated by Django 6.0 on 2025-12-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0012_alter_simulatorflight_plane"),
        ("pilots", "0004_alter_pilot_licenses_alter_pilot_medical_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulatorflight",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_sim_instructor",
                to="pilots.pilot",
            ),
        ),
        migrations.AlterField(
            model_name="simulatorflight",
            name="pilot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_sim_pilot",
                to="pilots.pilot",
            ),
        ),
        migrations.DeleteModel(
            name="Simulator",
        ),
    ]
