# Generated by Django 6.0 on 2025-12-29 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0013_alter_simulatorflight_instructor_and_more"),
        ("routes", "0003_airport_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.route",
            ),
        ),
    ]
