# Generated by Django 6.0 on 2025-12-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0014_alter_flight_route"),
        ("routes", "0003_airport_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routes.route"
            ),
        ),
        migrations.AlterField(
            model_name="simulatorflight",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.route",
            ),
        ),
    ]
