# Generated by Django 6.0 on 2026-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0015_alter_flight_route_alter_simulatorflight_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
    ]
