# Generated by Django 6.0 on 2026-03-08 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0016_flight_excluded"),
        ("routes", "0003_airport_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="holds",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Approach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport",
                        to="routes.airport",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approaches",
                        to="flights.flight",
                    ),
                ),
            ],
        ),
    ]
