# Generated by Django 6.0 on 2025-12-26 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
        ("pilots", "0005_remove_pilot_licenses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="name",
        ),
        migrations.AddField(
            model_name="license",
            name="pilot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="pilots.pilot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="license",
            name="type",
            field=models.CharField(default="PPL", max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="license",
            name="expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
