# Generated by Django 6.0 on 2025-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_remove_license_name_license_pilot_license_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="type",
            field=models.CharField(
                choices=[
                    ("PPL", "Private"),
                    ("INS", "Instrument"),
                    ("CFI", "Certified Flight Instructor"),
                    ("CFII", "Certified Flight Instructor w/ Instrument"),
                ],
                max_length=6,
            ),
        ),
    ]
