# Generated by Django 6.0 on 2025-12-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_alter_license_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="type",
            field=models.CharField(
                choices=[
                    ("PPL", "Private Pilot"),
                    ("INS", "Instrument"),
                    ("CFI", "Certified Flight Instructor"),
                    ("CFII", "Certified Flight Instructor w/ Instrument"),
                ],
                max_length=6,
            ),
        ),
    ]
